stages:
    - setup
    - test
    - package

cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
variables:
    MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    MYSQL_DATABASE: shopware
    MYSQL_USER: shopware
    MYSQL_PASSWORD: shopware

    SHOPWARE_VERSION: "v5.7.0" # Tag
    COMPOSER_COMMAND: "composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader"

setup:
    stage: setup
    image: "edbizarro/gitlab-ci-pipeline-php:7.4"
    script:
        - mkdir -p /tmp/opt
        - git clone -b ${SHOPWARE_VERSION} https://github.com/shopware5/shopware "/tmp/opt/shopware"
        - cd /tmp/opt/shopware && ${COMPOSER_COMMAND}
        - cp -r ${CI_PROJECT_DIR} /tmp/opt/shopware/custom/plugins/UnzerPayment && cd /tmp/opt/shopware/custom/plugins/UnzerPayment && ${COMPOSER_COMMAND}
        - cd /tmp/opt/shopware && composer dump-autoload -d custom/plugins/UnzerPayment
        - cp -r /tmp/opt/shopware ${CI_PROJECT_DIR}/sw_dir
    artifacts:
        paths:
            - "sw_dir"
        expire_in: 1 days
        when: always

codestyle:
    stage: test
    image: "edbizarro/gitlab-ci-pipeline-php:7.4"
    needs:
        - job: setup
          artifacts: true
    script:
        - cd ${CI_PROJECT_DIR}/sw_dir/custom/plugins/UnzerPayment && vendor/bin/php-cs-fixer fix -v --dry-run
    cache:
        key: global
        paths:
            - .php_cs.cache

k10r-phpstan:
    stage: test
    image: "edbizarro/gitlab-ci-pipeline-php:7.4"
    needs:
        - job: setup
          artifacts: true
    script:
        - cd ${CI_PROJECT_DIR}/sw_dir/custom/plugins/UnzerPayment && vendor/bin/phpstan analyse .

sw-phpstan:
    stage: test
    image: "edbizarro/gitlab-ci-pipeline-php:7.4"
    needs:
        - job: setup
          artifacts: true
    before_script:
        - cd /tmp && git clone https://github.com/shopwareLabs/store-plugin-codereview.git && store-plugin-codereview && ${COMPOSER_COMMAND}
        - cp -r /tmp/store-plugin-codereview/configs/phpstan/phpstan.neon.sw5 ${CI_PROJECT_DIR}/sw_dir/custom/plugins/UnzerPayment/phpstan_sw.neon
    script:
        - cd ${CI_PROJECT_DIR}/sw_dir/custom/plugins/UnzerPayment && vendor/bin/phpstan analyse -c phpstan_sw.neon -a vendor/autoload.php -a ../../../vendor/autoload.php .

shopware-validate:
    allow_failure: true
    image:
        name: friendsofshopware/plugin-uploader:0.3.5
        entrypoint: [ "/bin/sh", "-c" ]
    stage: test
    only:
        - tags
        - master
        - /^fix.*$/
    needs:
        - job: setup
          artifacts: true
    before_script:
        - rm -rf sw_dir
    script:
        - php /app/bin/pluginupload ext:zip . $CI_COMMIT_SHA
        - php /app/bin/pluginupload ext:validate *$CI_COMMIT_SHA.zip

package:
    image: kellerkinder/shopware-package-plugin:latest
    stage: package
    needs: []
    only:
        - tags
        - master
        - /^fix.*$/
        - /^integration.*$/
    script:
        - package-plugin UnzerPayment
    artifacts:
        paths:
            - UnzerPayment.zip
