stages:
  - setup
  - test

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

services:
  - mysql:5.7

variables:
  MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  MYSQL_DATABASE: shopware
  MYSQL_USER: shopware
  MYSQL_PASSWORD: shopware

  SHOPWARE_VERSION: "5.6.0"
  PLUGIN_NAME: "UnzerPayment"

composer:
  stage: setup
  image: "edbizarro/gitlab-ci-pipeline-php:7.2"
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader
  artifacts:
    paths:
      - vendor/
    expire_in: 1 days
    when: always
  cache:
    paths:
      - vendor/

codestyle:
  stage: test
  image: "edbizarro/gitlab-ci-pipeline-php:7.2"
  dependencies:
    - composer
  script:
    - vendor/bin/php-cs-fixer fix -v --dry-run
  cache:
    key: global
    paths:
      - .php_cs.cache

php-unit:
  image: "kellerkinder/shopware-testing:php71-1.0.0"
  stage: test
  dependencies:
    - composer
  script:
    - /usr/local/bin/clone-shopware "${CI_PROJECT_DIR}" ${SHOPWARE_VERSION}
    - mv ${CI_PROJECT_DIR}/opt /tmp/opt
    - cp -r ${CI_PROJECT_DIR} /tmp/opt/shopware-${SHOPWARE_VERSION}/custom/plugins/HeidelPayment
    - mv /tmp/opt ${CI_PROJECT_DIR}/opt
    - cd ${CI_PROJECT_DIR}/opt/shopware-${SHOPWARE_VERSION}/build && ant -Ddb.name=${MYSQL_DATABASE} -Ddb.host=mysql -Ddb.user=${MYSQL_USER} -Ddb.password=${MYSQL_PASSWORD} configure && ant build-unit
    - cd ${CI_PROJECT_DIR}/opt/shopware-${SHOPWARE_VERSION}/custom/plugins/${PLUGIN_NAME}
    - php ${CI_PROJECT_DIR}/opt/shopware-${SHOPWARE_VERSION}/composer.phar install -o
    - php ${CI_PROJECT_DIR}/opt/shopware-${SHOPWARE_VERSION}/bin/console sw:plugin:refresh -v
    - php ${CI_PROJECT_DIR}/opt/shopware-${SHOPWARE_VERSION}/bin/console sw:plugin:install --activate ${PLUGIN_NAME} -v
    - cd ${CI_PROJECT_DIR}/opt/shopware-${SHOPWARE_VERSION}/custom/plugins/${PLUGIN_NAME} && ${CI_PROJECT_DIR}/opt/shopware-${SHOPWARE_VERSION}/vendor/bin/phpunit
