name: Build Release ZIP

on:
  release:
    types: [created]

jobs:
  build-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Prepare ZIP file
      run: |
        mkdir -p build/UnzerPayment
        cp -r * build/UnzerPayment
        cp -r .* build/UnzerPayment || true
        rm -rf build/UnzerPayment/.git build/UnzerPayment/.github build/UnzerPayment/.githooks
        cd build
        zip -r UnzerPayment.zip UnzerPayment

    - name: Upload release asset
      uses: actions/upload-release-asset@v2
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/UnzerPayment.zip
        asset_name: UnzerPayment.zip
        content_type: application/zip
